### ISSUE TITLE
Instanz stellt Betrieb ein, wenn einzelnes Gerät nicht erreichbar

### ISSUE THREAD

**Issue by olderbag** [ioBroker/ioBroker.sonos#150]
**Describe the bug**  
Ich schalte einzelnen Lautsprechern, die teilweise Wochenlang nicht genutzt werden (z.B. Terrasse) per Aktor die Steckdose ab.
Dies führt offensichtlich dazu, dass der Adapter eine dauerhafte Störung erkennt und nicht mehr startet:
```
2022-04-21 08:15:36.865  - [31merror[39m: sonos.0 (21785) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

2022-04-21 08:15:36.866  - [31merror[39m: sonos.0 (21785) unhandled promise rejection: connect EHOSTUNREACH 192.168.1.65:1400

2022-04-21 08:15:36.867  - [31merror[39m: sonos.0 (21785) Error: connect EHOSTUNREACH 192.168.1.65:1400
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

2022-04-21 08:15:36.867  - [31merror[39m: sonos.0 (21785) Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.1.65:1400

2022-04-21 08:15:36.872  - [32minfo[39m: sonos.0 (21785) terminating
2022-04-21 08:15:36.879  - [32minfo[39m: sonos.0 (21785) terminating
2022-04-21 08:15:36.880  - [33mwarn[39m: sonos.0 (21785) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-21 08:15:37.495  - [31merror[39m: host.ioBroker instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

2022-04-21 08:15:37.495  - [32minfo[39m: host.ioBroker Restart adapter system.adapter.sonos.0 because enabled
2022-04-21 08:15:37.496  - [33mwarn[39m: host.ioBroker Do not restart adapter system.adapter.sonos.0 because restart loop detected
`''

Das Abschalten geschieht aus Gründen des Energie sparens. Sind bei 2 Play:1 immerhin ca. 6 W als Dauerlast.

**Versions:**  
 - Adapter version: 2.1.7
 - JS-Controller version: 4.0.21
 - Node version: 14.18.2
 - Operating system: debian

**Comment by Tomscloud** [comment]
Bei mir das selbe Problem, jetzt weis ich zumindest dass das passiert wenn Geräte ausgeschalten sind. 👍

**Comment by olderbag** [comment]
Wenn ich mal Zeit dafür finde, werde ich das Problem lösen, indem ich die SONOS Anbindung über NodeRed mache. Einstweilen nehme ich die temporär ausgeschalteten Geräte aus der Config.

**Comment by Apollon77** [comment]
Kann bitte jhe,and mal ein Debug Log posten von so einem Fall?

**Comment by olderbag** [comment]
Siehe mein Eröffnungspost.
So sieht das Log aus.

**Comment by Apollon77** [comment]
Ist aber kein Debug log :-)

**Comment by Tomscloud** [comment]
Bei mir ist der Log schon unten raus gelaufen, ich versuche es morgen zu provozieren :-)

**Comment by olderbag** [comment]
Ich warte gerade au h auf den nächsten Absturz.

**Comment by olderbag** [comment]
Adapter steht Logging auf "debug".
HIer das Log vom letzten Absturz:
`2022-05-04 23:20:05.812  - [31merror[39m: sonos.0 (31021) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-05-04 23:20:05.815  - [31merror[39m: sonos.0 (31021) unhandled promise rejection: Cannot read property 'baseUrl' of undefined
2022-05-04 23:20:05.816  - [31merror[39m: sonos.0 (31021) TypeError: Cannot read property 'baseUrl' of undefined
    at NotificationListener.topologyChange (/opt/iobroker/node_modules/sonos-discovery/lib/SonosSystem.js:109:30)
    at NotificationListener.emit (events.js:400:28)
    at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:117:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-05-04 23:20:05.817  - [31merror[39m: sonos.0 (31021) Cannot read property 'baseUrl' of undefined
2022-05-04 23:20:05.825  - [32minfo[39m: sonos.0 (31021) terminating
2022-05-04 23:20:05.827  - [32minfo[39m: sonos.0 (31021) terminating
2022-05-04 23:20:05.828  - [33mwarn[39m: sonos.0 (31021) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-04 23:20:06.574  - [31merror[39m: host.ioBroker instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-05-04 23:20:06.589  - [32minfo[39m: host.ioBroker Restart adapter system.adapter.sonos.0 because enabled
2022-05-04 23:20:36.747  - [32minfo[39m: host.ioBroker instance system.adapter.sonos.0 started with pid 10341
2022-05-04 23:20:38.096  - [34mdebug[39m: sonos.0 (10341) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-05-04 23:20:38.151  - [34mdebug[39m: sonos.0 (10341) Objects client ready ... initialize now
2022-05-04 23:20:38.153  - [34mdebug[39m: sonos.0 (10341) Objects create System PubSub Client
2022-05-04 23:20:38.155  - [34mdebug[39m: sonos.0 (10341) Objects create User PubSub Client
2022-05-04 23:20:38.241  - [34mdebug[39m: sonos.0 (10341) Objects client initialize lua scripts
2022-05-04 23:20:38.247  - [34mdebug[39m: sonos.0 (10341) Objects connected to redis: 127.0.0.1:9001
2022-05-04 23:20:38.307  - [34mdebug[39m: sonos.0 (10341) Redis States: Use Redis connection: 127.0.0.1:9000
2022-05-04 23:20:38.336  - [34mdebug[39m: sonos.0 (10341) States create System PubSub Client
2022-05-04 23:20:38.337  - [34mdebug[39m: sonos.0 (10341) States create User PubSub Client
2022-05-04 23:20:38.385  - [34mdebug[39m: sonos.0 (10341) States connected to redis: 127.0.0.1:9000
2022-05-04 23:20:38.726  - [32minfo[39m: sonos.0 (10341) starting. Version 2.1.7 in /opt/iobroker/node_modules/iobroker.sonos, node: v14.18.2, js-controller: 4.0.23
2022-05-04 23:20:39.408  - [31merror[39m: sonos.0 (10341) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-05-04 23:20:39.409  - [31merror[39m: sonos.0 (10341) unhandled promise rejection: Cannot read property 'baseUrl' of undefined
2022-05-04 23:20:39.411  - [31merror[39m: sonos.0 (10341) TypeError: Cannot read property 'baseUrl' of undefined
    at NotificationListener.topologyChange (/opt/iobroker/node_modules/sonos-discovery/lib/SonosSystem.js:109:30)
    at NotificationListener.emit (events.js:400:28)
    at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:117:17
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-05-04 23:20:39.411  - [31merror[39m: sonos.0 (10341) Cannot read property 'baseUrl' of undefined
2022-05-04 23:20:39.432  - [32minfo[39m: sonos.0 (10341) terminating
2022-05-04 23:20:39.435  - [32minfo[39m: sonos.0 (10341) terminating
2022-05-04 23:20:39.436  - [33mwarn[39m: sonos.0 (10341) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-04 23:20:40.050  - [31merror[39m: host.ioBroker instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-05-04 23:20:40.050  - [32minfo[39m: host.ioBroker Restart adapter system.adapter.sonos.0 because enabled
2022-05-04 23:21:07.219  - [32minfo[39m: javascript.0 (14448) script.js.common.Temperatur_Farbwerte.Salon: 22.4
2022-05-04 23:21:07.220  - [32minfo[39m: javascript.0 (14448) script.js.common.Temperatur_Farbwerte.Salon: greenyellow
2022-05-04 23:21:10.225  - [32minfo[39m: host.ioBroker instance system.adapter.sonos.0 started with pid 11174
2022-05-04 23:21:11.646  - [34mdebug[39m: sonos.0 (11174) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-05-04 23:21:11.701  - [34mdebug[39m: sonos.0 (11174) Objects client ready ... initialize now
2022-05-04 23:21:11.708  - [34mdebug[39m: sonos.0 (11174) Objects create System PubSub Client
2022-05-04 23:21:11.710  - [34mdebug[39m: sonos.0 (11174) Objects create User PubSub Client
2022-05-04 23:21:11.833  - [34mdebug[39m: sonos.0 (11174) Objects client initialize lua scripts
2022-05-04 23:21:11.841  - [34mdebug[39m: sonos.0 (11174) Objects connected to redis: 127.0.0.1:9001
2022-05-04 23:21:11.890  - [34mdebug[39m: sonos.0 (11174) Redis States: Use Redis connection: 127.0.0.1:9000
2022-05-04 23:21:11.919  - [34mdebug[39m: sonos.0 (11174) States create System PubSub Client
2022-05-04 23:21:11.920  - [34mdebug[39m: sonos.0 (11174) States create User PubSub Client
2022-05-04 23:21:11.969  - [34mdebug[39m: sonos.0 (11174) States connected to redis: 127.0.0.1:9000
2022-05-04 23:21:12.429  - [32minfo[39m: sonos.0 (11174) starting. Version 2.1.7 in /opt/iobroker/node_modules/iobroker.sonos, node: v14.18.2, js-controller: 4.0.23
2022-05-04 23:21:13.467  - [31merror[39m: sonos.0 (11174) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-05-04 23:21:13.468  - [31merror[39m: sonos.0 (11174) unhandled promise rejection: Cannot read property 'baseUrl' of undefined
2022-05-04 23:21:13.469  - [31merror[39m: sonos.0 (11174) TypeError: Cannot read property 'baseUrl' of undefined
    at NotificationListener.topologyChange (/opt/iobroker/node_modules/sonos-discovery/lib/SonosSystem.js:109:30)
    at NotificationListener.emit (events.js:400:28)
    at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:117:17
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-05-04 23:21:13.470  - [31merror[39m: sonos.0 (11174) Cannot read property 'baseUrl' of undefined
2022-05-04 23:21:13.482  - [32minfo[39m: sonos.0 (11174) terminating
2022-05-04 23:21:13.484  - [32minfo[39m: sonos.0 (11174) terminating
2022-05-04 23:21:13.486  - [33mwarn[39m: sonos.0 (11174) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-04 23:21:14.093  - [31merror[39m: host.ioBroker instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-05-04 23:21:14.094  - [32minfo[39m: host.ioBroker Restart adapter system.adapter.sonos.0 because enabled
2022-05-04 23:21:14.094  - [33mwarn[39m: host.ioBroker Do not restart adapter system.adapter.sonos.0 because restart loop detected`

**Comment by olderbag** [comment]
Vielleicht beser als Textfile:
[sonos.txt](https://github.com/ioBroker/ioBroker.sonos/files/8629289/sonos.txt)

**Comment by Apollon77** [comment]
Aber der Fehler hier ist ein anderer wie der oben ...

**Comment by olderbag** [comment]
Die **Ursache** ist mglw. eine andere. Das Ergebnis ist das Gleiche:
`Do not restart adapter system.adapter.sonos.0 because restart loop detected`

Ich kann das Log und da die Ursache(n) leider nicht interpretieren. Ich helfe gerne, wenn man mir sagt "Mach bitte mal dies" oder "Mach bitte ma das". 

Zu den beiden Logs kann ich aber sagen:

Im ersten Log steht ja klar eine IP drin, die nicht erreicht werden konnte. Das ist einer der beiden Play:1 auf der Terrasse, die bei geschlossener Terrassentür abgeschaltet werden.

Zum Zeitpunkt des zweiten Logs waren nicht nur diese beiden abgeschaltet, sondern auch (kurz vorher) die Playbar, IP 192.168.1.61. Diese war mal das erste Gerät im System und dient eventuell als eine Art zentraler Koordinator, wobei das in der Konfig der SONOS App nicht ersichtlich ist.

**Comment by Apollon77** [comment]
So, also für die ECONNRESET und EHOSTUNREACH  Fälle bitte mal die GitHub version versuchen ... DIese "ignoriert" jetzt diese Fehler ... ich habe nur Null ahnung was dann passiert. Entweder es tut alles und er erkennt wenn die Geräte neu wieder online kommen und so oder er bekommt das nicht mit und wir enden" stuck" quasi. probiert es bitte mal
