### ISSUE TITLE
Unhandled  promise rejection - Cannot read properties of undefined (reading 'members')

### ISSUE THREAD

**Issue by Dreiviertelblut** [ioBroker/ioBroker.sonos#170]
I'm switching a pair of Sonos One Speaker (stereo) off on regular base by smart power plug (due to relatively high engergy consumption  in standby mode). Whenever swiching this pair ON, though, the adapter creates an error that causes it to stop and restart.  

**Screenshots & Logfiles**  
host.IOBroker | 2022-08-10 06:16:34.540 | info | instance system.adapter.sonos.0 started with pid 6361
-- | -- | -- | --
host.IOBroker | 2022-08-10 06:16:04.454 | info | Restart adapter system.adapter.sonos.0 because enabled
host.IOBroker | 2022-08-10 06:16:04.446 | error | instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
sonos.0 | 2022-08-10 06:16:03.731 | error | Cannot read properties of undefined (reading 'members')
sonos.0 | 2022-08-10 06:16:03.729 | error | TypeError:  Cannot read properties of undefined (reading 'members')    at  Player.recalculateGroupVolume  (/opt/iobroker/node_modules/sonos-discovery/lib/prototypes/Player/recalculateGroupVolume.js:4:32)     at NotificationListener.notificationHandler  (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:370:25)     at NotificationListener.emit (node:events:539:35)    at  /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:125:17     at runMicrotasks (<anonymous>)    at processTicksAndRejections  (node:internal/process/task_queues:96:5)
sonos.0 | 2022-08-10 06:16:03.728 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'members')
sonos.0 | 2022-08-10 06:16:03.701 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

**Versions:**  
 - Adapter version: 2.2.3
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: linux - buster

I wonder, if anyone else has idenified this problem or knows, how to prevent that.

**Comment by gttrmnn** [comment]
Same here 

<html>
<body>


sonos.0 | 2022-10-25 09:12:10.043 | info | starting. Version 2.2.3 in /opt/iobroker/node_modules/iobroker.sonos, node: v16.18.0, js-controller: 4.0.23
-- | -- | -- | --
sonos.0 | 2022-10-25 09:11:36.821 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sonos.0 | 2022-10-25 09:11:36.819 | info | terminating
sonos.0 | 2022-10-25 09:11:36.809 | info | terminating
sonos.0 | 2022-10-25 09:11:36.801 | error | Cannot read properties of undefined (reading 'members')
sonos.0 | 2022-10-25 09:11:36.800 | error | TypeError: Cannot read properties of undefined (reading 'members') at Player.recalculateGroupVolume (/opt/iobroker/node_modules/sonos-discovery/lib/prototypes/Player/recalculateGroupVolume.js:4:32) at NotificationListener.notificationHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:370:25) at NotificationListener.emit (node:events:525:35) at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:125:17 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)
sonos.0 | 2022-10-25 09:11:36.798 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'members')
sonos.0 | 2022-10-25 09:11:36.796 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>

Adapter version: 2.2.3
JS-Controller version: 4.0.23
Node version: v16.18.0
Operating system: linux, Debian 11 - bullseye (docker)

**Comment by mczeus** [comment]
Here's the same! You should save electricity, so I switch my sounbar completely without power. After switching on again then the error message.
A bug fix would be really great.

**Comment by Dreiviertelblut** [comment]
Thanks for looking into this. Correct, just a very unpleasant adapter restart. ;-)

**Comment by macpo** [comment]
I have the same issue with SONOS Ones and a Beam, which triggers an adapter restart.

Adapter version: 3.0.0
JS-Controller version: 6.0.11
Node version: v20.17.0
Operating system: Linux, Debian 12
