### ISSUE TITLE
Sonos Error Log

### ISSUE THREAD

**Issue by SlipKoRn88** [ioBroker/ioBroker.sonos#192]
Ich habe seit kurzer Zeit folgende Fehler im Log und kann diese nicht zuordnen. Zuvor habe ich nichts geändert. Hat das eventuell was mit den letzten Updates der Sonos App / Software zu tun?

Sonos Adapter:  2.2.3

`<html>
<body>

Nachricht
--
sonos.0 | 2023-03-31 12:28:36.620 | error | RequestFailedError: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2023-03-31 12:09:55.880 | error | Cannot replaceWithFavorite: RequestFailedError: Got status 500 when invoking /MediaRenderer/AVTransport/Control
host.pi | 2023-03-31 12:07:48.264 | error | instance system.adapter.sonos.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
sonos.0 | 2023-03-31 12:07:47.570 | error | Cannot read properties of undefined (reading 'members')
sonos.0 | 2023-03-31 12:07:47.570 | error | TypeError: Cannot read properties of undefined (reading 'members') at Player.recalculateGroupVolume (/opt/iobroker/node_modules/sonos-discovery/lib/prototypes/Player/recalculateGroupVolume.js:4:32) at NotificationListener.notificationHandler (/opt/iobroker/node_modules/sonos-discovery/lib/models/Player.js:370:25) at NotificationListener.emit (node:events:525:35) at /opt/iobroker/node_modules/sonos-discovery/lib/NotificationListener.js:125:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sonos.0 | 2023-03-31 12:07:47.569 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'members')
sonos.0 | 2023-03-31 12:07:47.569 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2023-03-31 12:03:57.590 | error | RequestFailedError: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2023-03-31 12:02:59.820 | error | RequestFailedError: Got status 500 when invoking /MediaRenderer/AVTransport/Control
sonos.0 | 2023-03-31 12:02:43.671 | error | RequestFailedError: Got status 500 when invoking /MediaRenderer/AVTransport/Control

</body>
</html>`

**Comment by a-i-ks** [comment]
Ich habe das gleiche Problem seit ein paar Tagen. Trat bei mir nach einem Stromausfall auf. Vermutlich hat sich die Sonos Box danach geupdatet. 
Hat jemand eine Idee?

**Comment by a-i-ks** [comment]
Ich habe die Ursache gefunden: Der Adapter gibt diese Fehlermeldung aus, wenn man den Play Command sendet, aber keine Musik in der Wiedergabeliste ist. Das erklärt auch das Auftreten nach einem Stromausfall. Der Wiedergabe State wurde dadurch geleert.
