### ISSUE TITLE
Uncaught Exception: Without reason

### ISSUE THREAD

**Issue by Olaf0202** [ioBroker/ioBroker.sonos#225]
**Describe the bug**  
Just installed the sonos adapter and instantly received those error messages:

```
sonos.0 | 2024-02-16 09:47:39.514 | info | terminating
sonos.0 | 2024-02-16 09:47:39.035 | error | sonos is not an object of type "meta"
sonos.0 | 2024-02-16 09:47:39.035 | error | Error: sonos is not an object of type "meta" at ObjectsInRedisClient.validateMetaObject (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:591:35) at ObjectsInRedisClient.writeFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:824:24) at AdapterClass.writeFile (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:4819:73) at /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2022:16 at new Promise (<anonymous>) at AdapterClass.writeFileAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2021:16) at takeSonosState (/opt/iobroker/node_modules/iobroker.sonos/main.js:1456:31) at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1693:17) at SonosSystem.<anonymous> (/opt/iobroker/node_modules/iobroker.sonos/main.js:2105:13) at SonosSystem.emit (node:events:517:28)
sonos.0 | 2024-02-16 09:47:39.033 | error | unhandled promise rejection: sonos is not an object of type "meta"
sonos.0 | 2024-02-16 09:47:39.033 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2024-02-16 09:47:39.014 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sonos.0 | 2024-02-16 09:47:39.013 | info | terminating
sonos.0 | 2024-02-16 09:47:39.011 | info | terminating
sonos.0 | 2024-02-16 09:47:39.010 | error | Cannot write file coverImage/192_168_178_29.png: sonos is not an object of type "meta"
sonos.0 | 2024-02-16 09:47:39.005 | error | sonos is not an object of type "meta"
sonos.0 | 2024-02-16 09:47:39.005 | error | Error: sonos is not an object of type "meta" at ObjectsInRedisClient.validateMetaObject (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:587:39) at async ObjectsInRedisClient.writeFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:824:13)
sonos.0 | 2024-02-16 09:47:39.005 | error | unhandled promise rejection: sonos is not an object of type "meta"
sonos.0 | 2024-02-16 09:47:39.004 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sonos.0 | 2024-02-16 09:47:38.992 | error | Cannot write file coverImage/192_168_178_36.png: sonos is not an object of type "meta"
sonos.0 | 2024-02-16 09:47:37.992 | info | starting. Version 3.0.0 in /opt/iobroker/node_modules/iobroker.sonos, node: v18.19.0, js-controller: 5.0.17
```

**Versions:**  
 - Adapter version: v2.3.1
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: Debian

**Comment by Apollon77** [comment]
It seems as if there are some objects and data not created as they should on install. Please try to delete the instance and add again. Please show after the installment the sonos object tree as screenshot. Thank you

**Comment by Olaf0202** [comment]
Right after the installation the adapter works fine without any error messages. I just reinstalled it and deleted the remaining object folder. Please find a screenschot of the object tree after the installation.
As soon as I add back my sonos devices, it fails again with the above mentioned error message
![Sonos-ObjectTree](https://github.com/ioBroker/ioBroker.sonos/assets/160222535/f2ad2597-ca7a-46d4-8e6d-107eb114a503)

**Comment by Apollon77** [comment]
WHich js-controller version you use? In my system it looks like this

![Bildschirmfoto 2024-04-21 um 21 48 43](https://github.com/ioBroker/ioBroker.sonos/assets/11976694/d7e67fe7-dd51-43c5-86a4-3c64fba868a0)

do you see the "meta" i the most top "sonos" line ... thats the way it needs to be

**Comment by Apollon77** [comment]
Pleasd delete and install adapter again

**Comment by Eulili** [comment]
After several times of installing the adapter again, it seem that the "meta" is not given. Is there any way to edit it anywhere?!?
