### ISSUE TITLE
1.7.6. TTS does not work anymore

### ISSUE THREAD

**Issue by thenikoboxman** [ioBroker/ioBroker.sonos#33]
The sayit does not work anymore since 1.7.6 
Is there a way to downgrade to 1.7.4 or 1.6.2? These versions worked

Log says:
sonos.0 | 2018-08-27 22:47:53.533 | info | http sonos server listening on port 8080
sonos.0 | 2018-08-27 22:47:53.512 | info | starting. Version 1.7.6 in /opt/iobroker/node_modules/iobroker.sonos, node: v8.11.4
sonos.0 | 2018-08-27 22:47:20.785 | info | terminating
sonos.0 | 2018-08-27 22:47:20.770 | info | terminating
sonos.0 | 2018-08-27 22:47:20.765 | error | at Timer.listOnTimeout (timers.js:290:5)
sonos.0 | 2018-08-27 22:47:20.765 | error | at tryOnTimeout (timers.js:323:5)
sonos.0 | 2018-08-27 22:47:20.765 | error | at ontimeout (timers.js:508:15)
sonos.0 | 2018-08-27 22:47:20.765 | error | at Timeout.playOnSonos [as _onTimeout] (/opt/iobroker/node_modules/iobroker.sonos/main.js:1015:9)
sonos.0 | 2018-08-27 22:47:20.765 | error | at fadeOut (/opt/iobroker/node_modules/iobroker.sonos/main.js:821:38)
sonos.0 | 2018-08-27 22:47:20.765 | error | TypeError: Cannot read property 'actual' of undefined
sonos.0 | 2018-08-27 22:47:20.764 | error | uncaught exception: Cannot read property 'actual' of undefined

```
Blockly script for test:
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="on" id="C28rU(g@cUlNr-Yxpa-;" x="163" y="388">
    <field name="OID">cloud.1.services.ifttt</field>
    <field name="CONDITION">any</field>
    <field name="ACK_CONDITION"></field>
    <statement name="STATEMENT">
      <block type="controls_if" id="@5QrqlYJh;UW5ukVI=1K">
        <value name="IF0">
          <block type="logic_compare" id="3+{vuTd8NuZ47B{e-6k[">
            <field name="OP">EQ</field>
            <value name="A">
              <block type="get_value" id="UQ1Q~O[b-wB28s~x|A!~">
                <field name="ATTR">val</field>
                <field name="OID">cloud.1.services.ifttt</field>
              </block>
            </value>
            <value name="B">
              <block type="text" id="fh#A~Bgmbx|21=0Jc77s">
                <field name="TEXT">sonos</field>
              </block>
            </value>
          </block>
        </value>
        <statement name="DO0">
          <block type="sayit" id="3dkJ!/2[Pf`X^VD+b8L2">
            <field name="INSTANCE">.1</field>
            <field name="LANGUAGE"></field>
            <field name="LOG"></field>
            <value name="MESSAGE">
              <shadow type="text" id="zM^nm,p:m[cnfeg{LYA[">
                <field name="TEXT">Das ist ein Test</field>
              </shadow>
            </value>
          </block>
        </statement>
      </block>
    </statement>
  </block>
</xml>

```

**Comment by thenikoboxman** [comment]
Works again. Thank you

Am Mo., 27. Aug. 2018 um 23:24 Uhr schrieb Bluefox <notifications@github.com
