### ISSUE TITLE
Error with js-controller 1.5.14

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.sonos#46]
On a new iobroker installtion, with the new installtion script and js-controller version 1.5.14, the datapoint of the sonos speaker are not getting update and the adapter is starting new alle the time and creating the following log entries:

`
2019-07-30 19:05:52.116 - info: sonos.0 terminating
2019-07-30 19:05:52.124 - error: sonos.0 Got error: Parse Error
2019-07-30 19:05:52.167 - error: Caught by controller[1]: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
2019-07-30 19:05:52.167 - error: Caught by controller[1]: at maybeCallback (fs.js:128:9)
2019-07-30 19:05:52.168 - error: Caught by controller[1]: at Object.exists (fs.js:196:3)
2019-07-30 19:05:52.168 - error: Caught by controller[1]: at ClientRequest.http.get.res2 (/opt/iobroker/node_modules/iobroker.sonos/main.js:1783:37)
2019-07-30 19:05:52.168 - error: Caught by controller[1]: at Object.onceWrapper (events.js:286:20)
2019-07-30 19:05:52.168 - error: Caught by controller[1]: at ClientRequest.emit (events.js:198:13)
2019-07-30 19:05:52.169 - error: Caught by controller[1]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
2019-07-30 19:05:52.169 - error: Caught by controller[1]: at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
2019-07-30 19:05:52.169 - error: Caught by controller[1]: at Socket.socketOnData (_http_client.js:442:20)
2019-07-30 19:05:52.170 - error: Caught by controller[1]: at Socket.emit (events.js:198:13)
2019-07-30 19:05:52.170 - error: Caught by controller[1]: at addChunk (_stream_readable.js:288:12)
2019-07-30 19:05:52.170 - error: Caught by controller[1]: at readableAddChunk (_stream_readable.js:269:11)
2019-07-30 19:05:52.170 - error: Caught by controller[1]: at Socket.Readable.push (_stream_readable.js:224:10)
2019-07-30 19:05:52.171 - error: Caught by controller[1]: at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2019-07-30 19:05:52.171 - error: host.iobroker instance system.adapter.sonos.0 terminated with code 0 (OK)
2019-07-30 19:05:52.171 - info: host.iobroker Restart adapter system.adapter.sonos.0 because enabled
2019-07-30 19:06:22.198 - info: host.iobroker instance system.adapter.sonos.0 started with pid 21570
2019-07-30 19:06:24.125 - info: sonos.0 starting. Version 1.8.0 in /opt/iobroker/node_modules/iobroker.sonos, node: v10.16.0
2019-07-30 19:06:24.241 - info: sonos.0 http sonos server listening on port 8080
`

On my older test installation with js-controller version 1.5.12 it is working fine.

I tried it with the adapter version 1.7.7 and 1.8.0 with the same result.

**Comment by Hesse-Bub** [comment]
I did a new installation and received the following messages:

`
2019-08-01 20:46:31.869 - info: sonos.0 terminating
2019-08-01 20:46:31.966 - error: Caught by controller[0]: (node:8791) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
2019-08-01 20:46:31.971 - error: Caught by controller[0]: at isRadio (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/prototypes/Player/getUriType.js:4:14)
2019-08-01 20:46:31.972 - error: Caught by controller[0]: at Player.getUriType (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/prototypes/Player/getUriType.js:18:10)
2019-08-01 20:46:31.972 - error: Caught by controller[0]: at parseTrackMetadata.then.track (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:243:43)
2019-08-01 20:46:31.972 - error: Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-08-01 20:46:31.972 - error: Caught by controller[1]: (node:8791) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-08-01 20:46:31.972 - error: Caught by controller[1]: (node:8791) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-08-01 20:46:31.972 - error: Caught by controller[2]: (node:8791) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
2019-08-01 20:46:31.973 - error: Caught by controller[2]: at isRadio (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/prototypes/Player/getUriType.js:4:14)
2019-08-01 20:46:31.973 - error: Caught by controller[2]: at Player.getUriType (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/prototypes/Player/getUriType.js:18:10)
2019-08-01 20:46:31.973 - error: Caught by controller[2]: at parseTrackMetadata.then.track (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/models/Player.js:243:43)
2019-08-01 20:46:31.973 - error: Caught by controller[2]: at process._tickCallback (internal/process/next_tick.js:68:7)
2019-08-01 20:46:31.973 - error: Caught by controller[3]: (node:8791) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

`

**Comment by Apollon77** [comment]
Please retry GithUb version

**Comment by Hesse-Bub** [comment]
Thank you for the changes, I tried it, but the Datapoints still don't get any update (beside for example volume)

**Comment by Hesse-Bub** [comment]
It seems, that this is not working:

`        // patch socket
        if (fs.existsSync(staticPath + '/js/socket.js')) {
            let data = fs.readFileSync(staticPath + '/js/socket.js').toString();
            if (data.indexOf('io.connect(target);') !== -1) {
                data = data.replace('io.connect(target);', "io.connect('/', {path: location.pathname.replace('/m/', '/') + 'socket.io'}); // io.connect(target);");
                fs.writeFileSync(staticPath + '/js/socket.js', data);
            }
        }
        if (fs.existsSync(staticPath + '/js/all.js')) {
            let data = fs.readFileSync(staticPath + '/js/all.js').toString();
            if (data.indexOf('"/svg/mute_on.svg" : "/svg/mute_off.svg"') !== -1) {
                data = data.replace('"/svg/mute_on.svg" : "/svg/mute_off.svg"', '"svg/mute_on.svg" : "svg/mute_off.svg"');
                data = data.replace('"/images/browse_missing_album_art.png";', '"images/browse_missing_album_art.png";');
                fs.writeFileSync(staticPath + '/js/all.js', data);
            }
        }`

Also the files in the SonosCache are not created

**Comment by Hesse-Bub** [comment]
this is fixed in Version 2.0, thank you @GermanBluefox
