### ISSUE TITLE
Problem grouping Sonos speakers

### ISSUE THREAD

**Issue by MikeGermany** [ioBroker/ioBroker.sonos#71]
Hello folks,
hopefully somebody 's got a clue, what I'm doing wrong.
Using RasPi 4B I did install iobroker and the sonos adapter.
I tried several times to write a script grouping the sonos speakers at home.
Nothing worked. Neither using the .coordinator no the .add_to_group methods.

Here's the code I'm using:
`/* Sonos Gruppe bilden mit ElternBad + SWR3 abspielen */
var sElternBad = 'sonos.0.root.192_168_178_55'
var sCoord = sElternBad
var sKueche = 'sonos.0.root.192_168_178_51'
var sMobil = 'sonos.0.root.192_168_178_52'
var sSchlafzimmer = 'sonos.0.root.192_168_178_59'

setState(sCoord + '.coordinator', sElternBad)
setState(sCoord + '.add_to_group', sElternBad)
setState(sCoord + '.volume',25)

/* Küche  zur Gruppe hinzufügen */
setState(sKueche + '.add_to_group', sCoord)
// setState(sKueche + '.coordinator' , sElternBad)
setState(sKueche + '.volume',25)

/* Mobil zur Gruppe hinzufügen*/
setState(sMobil + '.add_to_group' , sCoord)
//setState('sMobil + '.coordinator', sCoord)
//setState(sMobil + '.volume',25)

/* Schlafzimmer zur Gruppe hinzufügen */
//setState(sSchlafzimmer + '.add_to_group', sCoord)
//setState(sSchlafzimmer + '.coordinator' , sCoord)
//setState(sSchlafzimmer + '.volume',25)

/* Gruppe aktivieren */
setState('sonos.0.root.192_168_178_55.group_volume',25)
setState('sonos.0.root.192_168_178_55.favorites_set',"SWR3")
// setState('sonos.0.root.192_168_178_55.play',true)
`
Although the datapoints are valid, I get the following messages in the LOG:
`
2020-05-21 17:17:13.563 - info: javascript.0 (1484) Start javascript script.js.common.Mappe_1.Testing_Sonos
--
2020-05-21 17:17:13.602 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.coordinator, state="sonos.0.root.192_168_178_55")
2020-05-21 17:17:13.603 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.add_to_group, state="sonos.0.root.192_168_178_55")
2020-05-21 17:17:13.604 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.volume, state=25)
2020-05-21 17:17:13.606 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_51.add_to_group, state="sonos.0.root.192_168_178_55")
2020-05-21 17:17:13.607 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.group_volume, state=25)
2020-05-21 17:17:13.608 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: registered 0 subscriptions and 0 schedules
2020-05-21 17:17:13.633 - info: sonos.0 (30069) try to control id sonos.0.root.192_168_178_55.coordinator with {"val":"sonos.0.root.192_168_178_55","ack":false,"ts":1590074233624,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1590074233624}
2020-05-21 17:17:13.649 - error: sonos.0 (30069) uncaught exception: Cannot read property 'uuid' of undefined
2020-05-21 17:17:13.650 - error: sonos.0 (30069) TypeError: Cannot read property 'uuid' of undefined
at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:53)
at Adapter. (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
at Adapter.emit (events.js:310:20)
at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4855:34)
at processImmediate (internal/timers.js:456:21)
2020-05-21 17:17:13.652 - info: sonos.0 (30069) terminating
2020-05-21 17:17:13.658 - info: sonos.0 (30069) try to control id sonos.0.root.192_168_178_55.add_to_group with {"val":"sonos.0.root.192_168_178_55","ack":false,"ts":1590074233625,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1590004827676}
2020-05-21 17:17:13.659 - info: sonos.0 (30069) try to control id sonos.0.root.192_168_178_55.volume with {"val":25,"ack":false,"ts":1590074233625,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1590074233625}
2020-05-21 17:17:13.662 - info: sonos.0 (30069) try to control id sonos.0.root.192_168_178_51.add_to_group with {"val":"sonos.0.root.192_168_178_55","ack":false,"ts":1590074233625,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1590074233625}
2020-05-21 17:17:13.663 - info: sonos.0 (30069) try to control id sonos.0.root.192_168_178_55.group_volume with {"val":25,"ack":false,"ts":1590074233625,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1590074233625}
2020-05-21 17:17:13.665 - error: sonos.0 (30069) uncaught exception: Cannot read property 'members' of undefined
2020-05-21 17:17:13.666 - error: sonos.0 (30069) TypeError: Cannot read property 'members' of undefined
at Player.setGroupVolume (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/prototypes/Player/setGroupVolume.js:17:25)
at Adapter. (/opt/iobroker/node_modules/iobroker.sonos/main.js:190:28)
at Adapter.emit (events.js:310:20)
at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4855:34)
at processImmediate (internal/timers.js:456:21)
2020-05-21 17:17:13.679 - info: sonos.0 (30069) terminating
2020-05-21 17:17:13.680 - info: sonos.0 (30069) Terminated (NO_ERROR): Without reason
2020-05-21 17:17:14.204 - error: host.raspberrypi Caught by controller[0]: TypeError: Cannot read property 'uuid' of undefined
2020-05-21 17:17:14.204 - error: host.raspberrypi Caught by controller[0]: at attachTo (/opt/iobroker/node_modules/iobroker.sonos/main.js:924:53)
2020-05-21 17:17:14.205 - error: host.raspberrypi Caught by controller[0]: at Adapter. (/opt/iobroker/node_modules/iobroker.sonos/main.js:187:25)
2020-05-21 17:17:14.205 - error: host.raspberrypi Caught by controller[0]: at Adapter.emit (events.js:310:20)
2020-05-21 17:17:14.205 - error: host.raspberrypi Caught by controller[0]: at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4855:34)
2020-05-21 17:17:14.206 - error: host.raspberrypi Caught by controller[0]: at processImmediate (internal/timers.js:456:21)
2020-05-21 17:17:14.206 - error: host.raspberrypi Caught by controller[1]: TypeError: Cannot read property 'members' of undefined
2020-05-21 17:17:14.206 - error: host.raspberrypi Caught by controller[1]: at Player.setGroupVolume (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/prototypes/Player/setGroupVolume.js:17:25)
2020-05-21 17:17:14.206 - error: host.raspberrypi Caught by controller[1]: at Adapter. (/opt/iobroker/node_modules/iobroker.sonos/main.js:190:28)
2020-05-21 17:17:14.207 - error: host.raspberrypi Caught by controller[1]: at Adapter.emit (events.js:310:20)
2020-05-21 17:17:14.207 - error: host.raspberrypi Caught by controller[1]: at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4855:34)
2020-05-21 17:17:14.207 - error: host.raspberrypi Caught by controller[1]: at processImmediate (internal/timers.js:456:21)
2020-05-21 17:17:14.207 - info: host.raspberrypi instance system.adapter.sonos.0 terminated with code 0 (NO_ERROR)
2020-05-21 17:17:14.208 - info: host.raspberrypi Restart adapter system.adapter.sonos.0 because enabled
2020-05-21 17:17:18.743 - info: javascript.0 (1484) Stop script script.js.common.Mappe_1.Testing_Sonos
2020-05-21 17:17:18.872 - info: javascript.0 (1484) Start javascript script.js.common.Mappe_1.Testing_Sonos
2020-05-21 17:17:18.884 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.coordinator, state="sonos.0.root.192_168_178_55")
2020-05-21 17:17:18.885 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.add_to_group, state="sonos.0.root.192_168_178_55")
2020-05-21 17:17:18.886 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.volume, state=25)
2020-05-21 17:17:18.887 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_51.add_to_group, state="sonos.0.root.192_168_178_55")
2020-05-21 17:17:18.887 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: setForeignState(id=sonos.0.root.192_168_178_55.group_volume, state=25)
2020-05-21 17:17:18.888 - info: javascript.0 (1484) script.js.common.Mappe_1.Testing_Sonos: registered 0 subscriptions and 0 schedules
2020-05-21 17:17:44.261 - info: host.raspberrypi instance system.adapter.sonos.0 started with pid 25578
2020-05-21 17:17:45.370 - info: sonos.0 (25578) starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.sonos, node: v12.16.2

Whatever I do, only 2 speakers get grouped.
Best Regards
-Mike

**Comment by justr1** [comment]
Hi Mike,
for me 'add_to/remove_from_group' always was confusing, because it works opposite to my expectations. Iirc you have to put the slave IP to 'master.add_to_group', not vice versa. And it's 'write only' and therefor the result is hidden (latest with 3rd speaker). So I'm using '.coordinator' only. The value is just the IP address with '_' (underscore) instead of '.' (dot) and without object structure (no 'sonos.0.root'). If coordinator is the own ID (e.g. '192_168_178_55'), then the speaker is standalone or master of group. If coordinator is another ID, the speaker is a slave of another speaker (grouped). That's it.
HTH, justr

**Comment by MikeGermany** [comment]
Thank you very much Jürgen,
this made the job!
-Mike
