### ISSUE TITLE
uncaught exception: Cannot read property 'browseAll' of undefined

### ISSUE THREAD

**Issue by ivosch68** [ioBroker/ioBroker.sonos#78]
Nur ein kleiner Schönheitsfehler (Version 2.1.0):

**Gegeben**: Mein gesamtes SONOS System wird nur bei Anwesenheit eingeschaltet. Ansonsten ist es vom Strom getrennt.
Häufig kommt es kurz nach dem Einschalten zu folgender Fehlermeldung des Adaptes:

**Fehler**:
2020-09-04 08:40:50.397 - error: sonos.0 (25550) uncaught exception: Cannot read property 'browseAll' of undefined
2020-09-04 08:40:50.403 - error: sonos.0 (25550) TypeError: Cannot read property 'browseAll' of undefined
at SonosSystem.getFavorites (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/prototypes/SonosSystem/getFavorites.js:4:29)
at processSonosEvents (/opt/iobroker/node_modules/iobroker.sonos/main.js:1700:19)
at SonosSystem. (/opt/iobroker/node_modules/iobroker.sonos/main.js:1947:9)
at SonosSystem.emit (events.js:315:20)
at NotificationListener.listChange (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/SonosSystem.js:42:11)
at NotificationListener.emit (events.js:315:20)
at EventEmitter. (/opt/iobroker/node_modules/iobroker.sonos/node_modules/sonos-discovery/lib/NotificationListener.js:146:15)
at EventEmitter.emit (events.js:315:20)
at SAXStream.onCloseTag (/opt/iobroker/node_modules/iobroker.sonos/node_modules/xml-flow/lib/xml-flow.js:131:15)
at SAXStream.emit (events.js:315:20)

**Vorschlag**:
Bitte fangt den Fehler ab und werft eine Warnung oder Infomeldung.

P.S. Danke für eure tolle Arbeit!

**Comment by Apollon77** [comment]
check 2.1.1 coming soon

**Comment by terceseman** [comment]
I'm using following version 2.1.7 but getting a similar exception:

![image](https://user-images.githubusercontent.com/101564300/159641576-2666dc3d-4086-46ea-a7c8-85d3ab9b35a2.png)

One of my Sonos devices (ARC) is powering down most time.
